package com.infosys.smartwater.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Abstract base entity providing common audit fields for all domain entities.
 *
 * <p>All entities in this system extend {@code BaseEntity} to inherit:
 * <ul>
 *   <li>{@code id}        — UUID primary key, generated by the JVM (not the DB).</li>
 *   <li>{@code createdAt} — auto-set by Hibernate on INSERT, never updated.</li>
 *   <li>{@code updatedAt} — auto-updated by Hibernate on every UPDATE.</li>
 * </ul>
 *
 * <p><b>Design note:</b> We use Hibernate's {@code @CreationTimestamp} and
 * {@code @UpdateTimestamp} instead of JPA's {@code @CreatedDate} /
 * {@code @LastModifiedDate} to avoid the requirement for a separate
 * {@code AuditorAware} bean and {@code @EnableJpaAuditing} at this stage.
 * JPA auditing with {@code @CreatedBy} / {@code @LastModifiedBy} will be
 * added in the Security module.</p>
 *
 * <p><b>UUID strategy:</b> {@code GenerationType.UUID} (Hibernate 6+) generates
 * UUID v4 values at the Java layer before INSERT, making IDs available
 * immediately after entity construction — safe for batch operations.</p>
 */
@MappedSuperclass
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public abstract class BaseEntity {

    /**
     * Universally unique identifier for the entity.
     * Generated by the JVM using UUID v4; never overwritten after creation.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    /**
     * Timestamp of when the record was first persisted.
     * Set automatically by Hibernate; {@code updatable = false} prevents drift.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp of the most recent update to the record.
     * Updated automatically by Hibernate on every flush.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
